package.loaded['runes'] = nil -- not needed in real usage, but worthy for developing runes
package.loaded['runes.spec'] = nil -- not needed in real usage, but worthy for developing runes
package.loaded['runes.test'] = nil -- not needed in real usage, but worthy for developing runes
package.loaded['runes.state'] = nil -- not needed in real usage, but worthy for developing runes
package.loaded['runes.default_asserts'] = nil -- not needed in real usage, but worthy for developing runes
package.loaded['runes.asserts.neovim'] = nil -- not needed in real usage, but worthy for developing runes
local runes = require("runes")

runes.deregister_assert("odd_assertion")
runes.register_assert("odd_assertion", function(x)
  return x > 2 and x < 5, "number is weird"
end)

local assert_tests = runes.spec{
  description = "Ensure asserts run correctly",
  assert_eq_works = function(assert)
    assert.eq['one should be equals to one'](1, 1)
  end,

  ['assert fail should fail'] = function(assert)
    assert.fail("expected failure")
  end,

  custom_assertions_work = function(assert)
    assert.odd_assertion['this should work'](3)
    assert.odd_assertion['this should break'](12)
  end,

  with_setup = runes.test{
    setup = function()
      return {"some", "magic", "state"}
    end,
    test = function(assert, state)
      assert.is_not_nil['state generated by setup is not nil'](state)
      assert.eq['state generated by setup is preserved'](#state, 3)
    end
  },

  runes.test{"neovim assertions work",
    test = function(assert)
      assert.buffer_exists['Current buffer should always exist'](0)
    end
  }
}

runes.run_spec(assert_tests)
